id: P009354
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG23715
  title: བློ་བཟང་དགོངས་རྒྱན་མུ་ཏིག་ཕྲེང་མཛེས་དེབ་གསུམ་པ།
  author: ''
  volumes:
    07d693a2fa574a00baeda2c902f5a3aa:
      image_group_id: I1KG23855
      title: ''
      volume_number: 1
      total_pages: 306
      base_file: v001.txt
